import pikepdf

from core.hashing import sha256_file

METADATA_KEY_DOCINFO = "/DocToPDFSourceHash"
METADATA_KEY_XMP = "pdfx:DocToPDFSourceHash"


class Result:
    MATCH = "match"
    MISMATCH = "mismatch"
    NO_METADATA = "no_metadata"
    ERROR = "error"


def validate(docx_path: str, pdf_path: str) -> tuple[str, str]:
    """Compare the DOCX hash against the hash embedded in the PDF.

    Returns (result_code, human-readable message).
    """
    try:
        source_hash = sha256_file(docx_path)
    except (OSError, IOError) as e:
        return Result.ERROR, f"Cannot read DOCX: {e}"

    try:
        with pikepdf.open(pdf_path) as pdf:
            # Try XMP first
            embedded_hash = None
            with pdf.open_metadata() as meta:
                embedded_hash = meta.get(METADATA_KEY_XMP)
            # Fallback to docinfo
            if not embedded_hash:
                raw = pdf.docinfo.get(METADATA_KEY_DOCINFO)
                if raw is not None:
                    embedded_hash = str(raw)
    except Exception as e:
        return Result.ERROR, f"Cannot read PDF: {e}"

    if not embedded_hash:
        return Result.NO_METADATA, (
            "This PDF does not contain a source hash.\n"
            "It was not generated by this tool."
        )

    if source_hash == embedded_hash:
        return Result.MATCH, "The PDF was generated from this DOCX file."
    else:
        return Result.MISMATCH, (
            "Hash mismatch. The PDF was not generated from this\n"
            "DOCX file, or the DOCX was modified after conversion."
        )
